# Where are all the schema files located? globs are supported eg  src/**/*.graphqls
schema:
  - api/graphql/schema.graphqls

exec:
  layout: follow-schema
  dir: internal/infra/graphql/graph
  package: graph

model:
  filename: internal/infra/graphql/graph/models_gen.go
  package: graph

resolver:
  layout: single-file
  dir: internal/infra/graphql/graph
  package: graph
  filename: resolver.go
  type: Resolver

struct_tag: json

skip_validation: true

autobind:
  - "desafio-cleanarchitecture/internal/infra/graphql/graph"

models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
